-- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/284527) 

SELECT SUM(SCORE) SCORE, HG.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES HE
JOIN HR_GRADE HG
ON HE.EMP_NO = HG.EMP_NO
WHERE YEAR = '2022'
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
